# Generated by Django 5.1.3 on 2024-12-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campos',
            fields=[
                ('campoid', models.AutoField(primary_key=True, serialize=False)),
                ('coordenadas', models.JSONField()),
                ('nome', models.TextField()),
                ('morada', models.TextField()),
                ('cidade', models.TextField()),
                ('pais', models.TextField()),
                ('datacriacao', models.DateField()),
                ('isactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargoid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Castas',
            fields=[
                ('castaid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(unique=True)),
                ('isactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'castas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('nome', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('telefone', models.TextField()),
                ('endereco', models.TextField()),
                ('isactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colheitas',
            fields=[
                ('colheitaid', models.AutoField(primary_key=True, serialize=False)),
                ('pesototal', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('precoportonelada', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('datapesagem', models.DateField(blank=True, null=True)),
                ('previsaofimcolheita', models.DateField(blank=True, null=True)),
                ('terminada', models.BooleanField()),
                ('isactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colheitas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('contratoid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('datainicio', models.DateField()),
                ('datafim', models.DateField(blank=True, null=True)),
                ('qtdeestimada', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('precoestimado', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('qtdefinal', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('precofinal', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('isactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contratos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadosaprovacoes',
            fields=[
                ('idaprovacao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
            options={
                'db_table': 'estadosaprovacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadosrecibo',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
            options={
                'db_table': 'estadosrecibo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadostransporte',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
            options={
                'db_table': 'estadostransporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metodospagamento',
            fields=[
                ('idmetodopagamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
            options={
                'db_table': 'metodospagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotasColheitas',
            fields=[
                ('notaid', models.AutoField(primary_key=True, serialize=False)),
                ('notas', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField()),
            ],
            options={
                'db_table': 'notas_colheitas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotasPedidos',
            fields=[
                ('notaid', models.AutoField(primary_key=True, serialize=False)),
                ('notas', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField()),
            ],
            options={
                'db_table': 'notas_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('pedidoid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('datainicio', models.DateField()),
                ('datafim', models.DateField(blank=True, null=True)),
                ('precoestimado', models.TextField(blank=True, null=True)),
                ('isactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidosItem',
            fields=[
                ('idpedido_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('isactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedidos_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('periodoid', models.AutoField(primary_key=True, serialize=False)),
                ('datainicio', models.DateField()),
                ('datafim', models.DateField()),
                ('ano', models.IntegerField()),
            ],
            options={
                'db_table': 'periodos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pesagens',
            fields=[
                ('pesagemid', models.AutoField(primary_key=True, serialize=False)),
                ('pesobruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pesoliquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datadepesagem', models.DateField()),
            ],
            options={
                'db_table': 'pesagens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('reciboid', models.AutoField(primary_key=True, serialize=False)),
                ('datainicio', models.DateField()),
                ('precofinal', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('isactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recibos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transportes',
            fields=[
                ('idtransporte', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('morada', models.TextField()),
                ('data', models.DateField()),
                ('precotransporte', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('precokm', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'transportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vinhas',
            fields=[
                ('vinhaid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('coordenadas', models.TextField()),
                ('dataplantacao', models.DateField(blank=True, null=True)),
                ('hectares', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('isactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vinhas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('clienteid', models.OneToOneField(db_column='clienteid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Backoffice.users')),
                ('isempresa', models.BooleanField()),
                ('nif', models.IntegerField()),
                ('contacto', models.TextField()),
                ('morada', models.TextField()),
                ('isactive', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
    ]
