from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    path ("" , views.home, name="home"),
    path('login/', views.login_view, name='login'),
    path('userdetail/<int:userid>/', views.userdetail, name='userdetail'),
    path('users/',  views.users, name='users'),
    path('user/<int:userid>/', views.userdetail, name='user-detail'),
    path('fields/', views.fields, name='fields'),
    path('save_marker/', views.save_marker_view, name='save_marker'),
    path('save_polygon/', views.save_polygon_view, name="save_polygon"),
    path('load_vineyards/', views.load_vineyards, name='load_vineyards'),
    path('home/', views.backofficeIndex, name='backofficeIndex'),
    path('delivery/',  views.delivery, name='delivery'),
    path('deliverydetail/',  views.deliverydetail, name='deliverydetail'),
    path('harvest/',  views.harvest, name='harvest'),
    path('harvestdetail/<int:colheitaid>/', views.harvestdetail, name='harvestdetail'),
    path('edit_pesagem/<int:pesagemid>/', views.edit_pesagem, name='edit_pesagem'),
    path('add_pesagem/<int:colheitaid>/', views.add_pesagem, name='add_pesagem'),
    path('delete_pesagem/<int:pesagemid>/', views.delete_pesagem, name='delete_pesagem'),
    path('add_note_harvest/<int:colheitaid>/', views.add_note_harvest, name='add_note_harvest'),
    path('edit_note_harvest/<int:notaid>/', views.edit_note_harvest, name='edit_note'), 
    path('delete_note_harvest/<int:notaid>/', views.delete_note_harvest, name='delete_note'),
    path('vineyards/',  views.load_vineyards_view, name='vineyards'),
    path('contracts/',  views.contracts, name='contracts'),
    path('contractdetail/<int:contratoid>/', views.contractdetail, name='contractdetail'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('request/', views.request, name='request'),
    path('add_request/', views.add_request, name='add_request'),
    path('add_note_request/<int:pedidoid>/', views.add_note_request, name='add_note_request'),
    path('edit_note_request/<int:notaid>/', views.edit_note_request, name='edit_note_request'),
    path('delete_note_request/<int:notaid>/', views.delete_note_request, name='delete_note_request'),
    path('update_request/<int:pedidoid>/', views.update_request, name='update_request'),
    path('delete_request/<int:pedidoid>/', views.delete_request, name='delete_request'),
    path('requestdetail/<int:pedidoid>/', views.requestdetail, name='requestdetail'),
    path('grapevariety/', views.grapevariety, name='grapevariety'),
    path('addvariety/', views.addvariety, name='addvariety'),
    path('deletevariety/<int:castaid>/', views.delete_variety, name='deletevariety'),
    path('editvariety/<int:castaid>/', views.editvariety, name='editvariety'),
    path('load_croplands/', views.load_croplands, name='load_croplands'),  
    path('get_campo_data/<int:campoid>/', views.get_campo_data, name='get_campo_data'),
    path('update_campo/<int:campoid>/', views.update_campo, name='update_campo'),
    path('delete_campo/<int:campoid>/', views.delete_campo, name='delete_campo'),
    path('payment_methods/', views.payment_methods, name='payment_methods'),
    path('addpaymentmethod/', views.add_payment_method, name='addpaymentmethod'),
    path('deletepaymentmethod/<int:method_id>/', views.delete_payment_method, name='deletepaymentmethod'),
    path('editpaymentmethod/<int:method_id>/', views.edit_payment_method, name='editpaymentmethod'),
]
